# ~/.config/starship.toml

[character]
success_symbol = "[✓](bold green) "
error_symbol = "[✗](bold red) "

[git_status]
ahead = "↑${count}"
behind = "↓${count}"
diverged = "${ahead_count}↕${behind_count}"
conflicted = "!${count}"
untracked = "?${count}"
stashed = "$${count}"
modified = "~${count}"
staged = "+${count}"
renamed = ">${count}"
deleted = "-${count}"


# 组件使用的符号改为字符 https://www.nerdfonts.com/cheat-sheet

[aws]
symbol = " "

[battery]
disabled = true
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[dart]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
