# ~/.config/starship.toml

# https://starship.rs/config

scan_timeout = 30000
command_timeout = 60000

[character]
success_symbol = '[>](bold green) '
error_symbol = '[x](bold red) '
vicmd_symbol = '[<](bold green) '

[line_break]
disabled = false

[jobs]
disabled = true

[battery]
disabled = true

[directory]
# truncation_length = 3
# truncation_symbol = '.../'

[shell]
disabled = true

[shlvl]
disabled = true

[status]

# [username]
# [hostname]
# [time]

[aws]
symbol = 'aws '
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[cmake]
symbol = 'cmake '
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = 'took [$duration]($style)'

[conda]
symbol = 'conda '
format = '\[[$symbol$environment]($style)\]'

[crystal]
symbol = 'crystal '
format = '\[[$symbol($version)]($style)\]'

[dart]
symbol = 'dart '
format = '\[[$symbol($version)]($style)\]'

[deno]
symbol = 'deno '
format = '\[[$symbol($version)]($style)\]'

[docker_context]
symbol = 'docker '
format = '\[[$symbol$context]($style)\]'

[dotnet]
symbol = '.NET '
format = '\[[$symbol($version)(什 $tfm)]($style)\]'

[elixir]
symbol = 'elixir '
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
symbol = 'elm '
format = '\[[$symbol($version)]($style)\]'

[erlang]
symbol = 'erlang '
format = '\[[$symbol($version)]($style)\]'

[gcloud]
symbol = 'gcloud '
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
symbol = 'git '
format = '\[[$symbol$branch]($style)\]'

[git_commit]
commit_hash_length = 8
tag_disabled = false
tag_symbol = 'tag '

[git_state]
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
format = '[\([$state($progress_current of $progress_total)]($style)\)]($style)'

[git_metrics]
disabled = true
format = '[+$added]($added_style) [-$deleted]($deleted_style)'

[git_status]
ahead = '↑${count}'
behind = '↓${count}'
diverged = '↑${ahead_count}↓${behind_count}'
conflicted = '!${count}'
untracked = '?${count}'
stashed = '#${count}'
modified = '~${count}'
staged = '+${count}'
renamed = '>${count}'
deleted = '-${count}'
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = 'go '
format = '\[[$symbol($version)]($style)\]'

[helm]
symbol = 'helm '
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
symbol = 'hg '
format = '\[[$symbol$branch]($style)\]'

[java]
symbol = 'java '
format = '\[[$symbol($version)]($style)\]'

[julia]
symbol = 'jl '
format = '\[[$symbol($version)]($style)\]'

[kotlin]
symbol = 'kt '
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
symbol = 'kubernetes '
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
symbol = 'lua '
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
disabled = true
symbol = 'memory '
format = '\[$symbol[$ram(\|$swap)]($style)\]'

[nim]
symbol = 'nim '
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
symbol = 'nix '
format = '\[[$symbol$state(\($name\))]($style)\]'

[nodejs]
symbol = 'nodejs '
format = '\[[$symbol($version)]($style)\]'

[ocaml]
symbol = 'ml '
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
symbol = 'openstack '
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]
symbol = 'pkg '
format = '\[[$symbol$version]($style)\]'

[perl]
symbol = 'pl '
format = '\[[$symbol($version)]($style)\]'

[php]
symbol = 'php '
format = '\[[$symbol($version)]($style)\]'

[purescript]
symbol = 'purs '
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = 'py '
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rlang]
symbol = 'rlang '
format = '\[[$symbol($version)]($style)\]'

[red]
symbol = 'red '
format = '\[[$symbol($version)]($style)\]'

[ruby]
symbol = 'rb '
format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = 'rs '
format = '\[[$symbol($version)]($style)\]'

[scala]
symbol = 'scala '
format = '\[[$symbol($version)]($style)\]'

[singularity]
symbol = 'singularity '
format = '\[[$symbol$env]($style)\]'

[swift]
symbol = 'swift '
format = '\[[$symbol($version)]($style)\]'

[terraform]
symbol = 'terraform '
format = '\[[$symbol$workspace]($style)\]'

[vagrant]
symbol = 'vagrant '
format = '\[[$symbol($version)]($style)\]'

[vcsh]
symbol = 'vcsh '
format = '\[[$symbol$repo]($style)\]'

[vlang]
symbol = 'vlang '
format = '\[[$symbol($version)]($style)\]'

[zig]
symbol = 'zig '
format = '\[[$symbol($version)]($style)\]'
